// Datos del tablero. Lo actualiza el agente product-owner antes de cada push.
// index.html solo los pinta: no hace falta tocarlo para mover tarjetas.
//
// estado: "por_hacer" | "en_curso" | "revision" | "hecho" | "bloqueado" | "descartado"
//         ("descartado" = cancelado o desestimado; solo lo decide el usuario. La nota empieza
//          por "Descartado por el usuario:" con el motivo y lo que se eligió)
// tipo:   "hito" | "seguridad" | "pendiente" | "decision" | "actividad"
//         ("actividad" = trabajo del proyecto que no es hito: repo, agentes, stages, tablero…)
// fase:   id de una fase de la lista "fases"; lo pospuesto fuera del MVP va en "V2".
// ids:    hitos como en docs/13; P- pendientes, S- seguridad, D- descartadas,
//         V- pospuestas a V2, A- actividades. Nunca se borran tarjetas.
window.TABLERO = {
  actualizado: "2026-10-06",
  rama: "fix/l2-estado-real",
  ultimo_commit: "f794683 docs(L2): estado real del hito: en curso, sin criterio cumplido",
  demo: "Demo MVP en workspace Azure de pago (stage mvp, Foundry)",

  fases: [
    { id: "L", nombre: "Fase L · Backend en local (notebooks)" },
    { id: "D", nombre: "Fase D · Despliegue en Databricks Free" },
    { id: "U", nombre: "Fase U · Interfaz" },
    { id: "Demo", nombre: "Demo · Azure + Foundry" },
    { id: "V2", nombre: "V2 · Fuera del MVP" },
  ],

  tarjetas: [
    // ── Hitos (docs/13) ──
    { id: "L0", fase: "L", tipo: "hito", estado: "hecho", titulo: "Base: config, errores y cliente de modelos",
      nota: "7/7 chequeos en 00_modelos.ipynb con Groq + bge-m3 reales en sandbox (criterio cumplido en f227b59). Después: Foundry listo para probar, correcciones appsec, stages dev/sandbox/mvp y proveedor DMR. qa-ia APROBADO (256530e, 68455a7): 163 unitarias, coverage 92 %, 8 de integración con Groq + bge-m3; criterios L0-L1 4 de 4 y RF/RNF verificados 1 de 28 (RF-04) según qa/trazabilidad.md. Tag v0.1.0 pendiente de publicar (ver A-10).", commit: "7c802a1" },
    { id: "L1", fase: "L", tipo: "hito", estado: "hecho", titulo: "Ingesta: validación + clasificación",
      nota: "6/6 chequeos en 01_ingesta.ipynb (Groq real). MOCK → manual_control, LA/FT → normativa (0,85). Rechazos con ERR-ING-001..003 y mensaje de negocio; un PDF reparado se acepta con advertencia y solo se rechaza con ERR-ING-003 si el texto no alcanza SCAN_TEXT_RATIO (5519d13, ver D-28). qa-ia APROBADO para el fix del PDF reparado: 168 unitarias passed, coverage 91 %, 8 de integración con Groq + bge-m3. Tag v0.2.0 pendiente de publicar (ver A-10).", commit: "0b4f926" },
    { id: "L2", fase: "L", tipo: "hito", estado: "en_curso", titulo: "Seccionado: Docling + cascada de patrones",
      nota: "Reabierto por decisión del usuario: se completa sobre feat/l2-seccionado. Hoy es el esqueleto de la herramienta agy, sin APROBADO de qa-ia; Docling no está instalado; el criterio (≥ 95 % de secciones y caché) no se ha medido. Ver implementacion/README.md y las tarjetas P-06..P-10, S-11 y S-12." },
    { id: "L3", fase: "L", tipo: "hito", estado: "por_hacer", titulo: "Recuperación: sub-chunks, embeddings, FAISS, pares",
      nota: "Recall ≥ 90 % sobre el golden set de los MOCK." },
    { id: "L4", fase: "L", tipo: "hito", estado: "por_hacer", titulo: "Juez: veredictos, citas verificadas, marcas A/L/R/X/P",
      nota: "MOCK-03 → A, MOCK-01 → L, MOCK-02 → R." },
    { id: "L5", fase: "L", tipo: "hito", estado: "por_hacer", titulo: "Papel de trabajo: Excel Hoja 1 + Hoja 2",
      nota: "Cero tokens al generar. Conteos Hoja 1 = Hoja 2." },
    { id: "L6", fase: "L", tipo: "hito", estado: "por_hacer", titulo: "Extremo a extremo: PDFs → Excel",
      nota: "Tiempos y RAM medidos en la Raspberry." },
    { id: "D0", fase: "D", tipo: "hito", estado: "por_hacer", titulo: "API FastAPI + sesión en memoria" },
    { id: "D1", fase: "D", tipo: "hito", estado: "por_hacer", titulo: "App en Databricks Free (app.yaml, < 10 MB)" },
    { id: "D2", fase: "D", tipo: "hito", estado: "por_hacer", titulo: "Ejemplos precargados (samples/)" },
    { id: "U0", fase: "U", tipo: "hito", estado: "por_hacer", titulo: "UI mínima en verde y blanco" },
    { id: "DEMO", fase: "Demo", tipo: "hito", estado: "por_hacer", titulo: "Ensayo con Foundry y documentos reales" },

    // ── Pendientes y verificaciones ──
    { id: "P-01", fase: "L", tipo: "pendiente", estado: "por_hacer", titulo: "Probar stage dev (MacBook, DMR)",
      nota: "Opcional, no bloquea (docs/13). Lo prueba el usuario." },
    { id: "P-02", fase: "Demo", tipo: "pendiente", estado: "por_hacer", titulo: "Probar stage mvp (Foundry en Databricks)",
      nota: "Celda comentada en 00_modelos.ipynb; token por dbutils." },
    { id: "P-03", fase: "L", tipo: "pendiente", estado: "por_hacer", titulo: "Calibrar SIM_THRESHOLD por stage",
      nota: "Con bge-m3 un par sin relación ya da ~0,50. Se calibra en L3 (docs/14 #1)." },
    { id: "P-04", fase: "L", tipo: "pendiente", estado: "por_hacer", titulo: "Calibrar LLM_CONCURRENCY con Groq gratuito",
      nota: "Ya se vieron 429 en L1. Se calibra en L4 (docs/14 #9)." },
    { id: "P-05", fase: "D", tipo: "pendiente", estado: "por_hacer", titulo: "D0: los metadatos editados por el auditor ganan a los del modelo",
      nota: "Anotado en implementacion/README.md, L1." },
    { id: "P-06", fase: "L", tipo: "pendiente", estado: "por_hacer", titulo: "L2: cola de 1 worker para Docling + progreso",
      nota: "CLAUDE.md regla 7: Docling en cola de un solo worker, do_ocr=False; con indicador de progreso." },
    { id: "P-07", fase: "L", tipo: "pendiente", estado: "por_hacer", titulo: "L2: cascada completa de seccionado",
      nota: "Tipografía, longitud, seccionado_incierto y ≥ 3 apariciones." },
    { id: "P-08", fase: "L", tipo: "pendiente", estado: "por_hacer", titulo: "L2: caché por SHA-256 del PDF",
      nota: "El criterio de L2 incluye la caché; sin medir." },
    { id: "P-09", fase: "L", tipo: "pendiente", estado: "por_hacer", titulo: "L2: medir ≥ 95 % de secciones en la LA/FT con RAM y CPU en la Raspberry",
      nota: "Instalar Docling y medir en 02_seccionado.ipynb; criterio de aceptación de L2 (docs/13)." },
    { id: "P-10", fase: "L", tipo: "pendiente", estado: "por_hacer", titulo: "L2: pruebas de qa-ia para el seccionado",
      nota: "Escribir y correr las pruebas de L2 (coverage ≥ 80 %, integración real) y actualizar qa/trazabilidad.md; sin APROBADO no se cierra el hito." },

    // ── Seguridad (agente appsec) ──
    { id: "S-01", fase: "L", tipo: "seguridad", estado: "por_hacer", titulo: "L4: chequeo de frases al evaluador → requiere_revision",
      nota: "Decisión del usuario (docs/14 #18)." },
    { id: "S-02", fase: "L", tipo: "seguridad", estado: "por_hacer", titulo: "L5: neutralizar fórmulas en el Excel (CWE-1236)",
      nota: "Todas las celdas de texto, incluidos metadatos y textos del modelo: prefijos =, +, -, @." },
    { id: "S-03", fase: "D", tipo: "seguridad", estado: "por_hacer", titulo: "D0: subidas con nombre generado, tope en streaming y timeout",
      nota: "MuPDF parsea entrada hostil." },
    { id: "S-04", fase: "D", tipo: "seguridad", estado: "por_hacer", titulo: "D0: /api/health sin detalle técnico y con caché",
      nota: "El ping gasta tokens. Además: cargar_prompt nunca con entrada del usuario." },
    { id: "S-05", fase: "L", tipo: "seguridad", estado: "por_hacer", titulo: "L4: rellenar el prompt del juez con rellenar_prompt",
      nota: "Ya existe desde L1 (clasificador). Auditoría appsec de L0." },
    { id: "S-06", fase: "L", tipo: "seguridad", estado: "hecho", titulo: "L1: validar %PDF, MAX_MB, MAX_PAGES y sanear el nombre",
      nota: "Hecho en validation.py; verificado en 01_ingesta.ipynb.", commit: "0b4f926" },
    { id: "S-07", fase: "L", tipo: "seguridad", estado: "hecho", titulo: "QA-01: rellenar_prompt con marcas anidadas o con atributos (MEDIA)",
      nota: "La neutralización de <texto_*> se podía saltar. Corregido y re-verificado por qa-ia (test_rellenar_prompt_marca_anidada_no_reconstruye_el_cierre, test_rellenar_prompt_quita_marca_con_atributos).", commit: "eda0014" },
    { id: "S-08", fase: "L", tipo: "seguridad", estado: "hecho", titulo: "DoS cuadrático en la neutralización de marcas (BAJA)",
      nota: "La neutralización pasa a ser lineal; corregido junto con QA-01.", commit: "eda0014" },

    // ── Actividades del proyecto (no son hitos) ──
    { id: "A-01", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Repo público basaravia/comparador-normas-v2",
      nota: "Creado y sincronizado. PDF del manual retirado de todo el historial; commits con la dirección noreply de GitHub.", commit: "6dec1f6" },
    { id: "A-02", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Worktree comparador-normas-v2-local con la rama feat/fase-l-local",
      nota: "Toda la fase L se trabajó en esta rama hasta L1; integrada en main y retirada (ver A-09)." },
    { id: "A-03", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Agente product-owner",
      nota: "Autoridad solo sobre plan y alcance (8da0562); supervisa el doc de implementación (implementacion/README.md, f705ca3).", commit: "d7233b4" },
    { id: "A-04", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Agente appsec (ciberseguridad aplicativa)",
      nota: "Revisa cada commit (ad885f8, 99e5e9c). Auditoría inicial de L0 con correcciones.", commit: "a8292be" },
    { id: "A-05", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Stages dev/sandbox/mvp y proveedor Docker Model Runner",
      nota: "Un archivo config/stages/<stage>.env por stage, elegido con STAGE (docs/14 #13).", commit: "7c802a1" },
    { id: "A-06", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Tablero de avance estilo Jira",
      nota: "Creado en f48c1bd. Ampliado con la columna Descartado y las actividades descartadas y pospuestas (48e6ad5).", commit: "f48c1bd" },
    { id: "A-07", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Agente qa-ia (QA de IA para auditoría financiera) y sus skills",
      nota: "Agente .claude/agents/qa-ia.md con las skills qa-pruebas, qa-trazabilidad y qa-eval-ia (.claude/skills/). Escribe solo en tests/, qa/ y pytest.ini; el agente principal lo verifica con git.", commit: "d9f46cf" },

    { id: "A-08", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Script tablero/servir.sh para ver el tablero en la red local",
      nota: "Sirve el tablero en la LAN sin publicarlo.", commit: "e41fbb2" },
    { id: "A-10", fase: "L", tipo: "actividad", estado: "por_hacer", titulo: "Publicar main y tags v0.1.0/v0.2.0",
      nota: "Publicar main y tags v0.1.0/v0.2.0 (bloqueado por falso positivo del guardián en tests/test_config.py: clave de prueba inventada; decisión del usuario pendiente)." },
    { id: "A-11", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Auditoría de L2 por PO, qa-ia y appsec",
      nota: "Resultado: L2 vuelve a en_curso y S-09 a revisión; hallazgos en P-06..P-10, S-11 y S-12." },
    { id: "A-12", fase: "L", tipo: "actividad", estado: "hecho", titulo: "La rama de agy con L2 subió sin revisión",
      nota: "Registrado como hecho del proceso, sin culpar a nadie: la rama llegó sin pasar por appsec, product-owner ni qa-ia (CLAUDE.md). Por eso se audita a posteriori (A-11)." },
    { id: "D-30", fase: "L", tipo: "decision", estado: "hecho", titulo: "Reabrir y completar L2 sobre feat/l2-seccionado; timeout de Docling en subproceso",
      nota: "Decisiones del usuario: L2 se reabre y se completa en feat/l2-seccionado; el timeout de Docling va en un subproceso con terminate() (ver S-09)." },
    { id: "A-09", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Integrar la rama larga feat/fase-l-local en main y retirarla",
      nota: "Integrada en main y retirada en este push; desde ahora ramas cortas desde main (D-27)." },

    // ── Descartadas por el usuario (y decisiones relacionadas) ──
    { id: "D-01", fase: "L", tipo: "decision", estado: "descartado", titulo: "Vía 2 en una tercera hoja del Excel",
      nota: "Descartado por el usuario: sin tercera hoja; se eligió un bloque al final del anexo, Hoja 2 (docs/14 #4)." },
    { id: "D-02", fase: "L", tipo: "decision", estado: "descartado", titulo: "Respaldo de hasta 2 secciones de manual para la marca L",
      nota: "Descartado por el usuario: se eligió 1 sección de respaldo por artículo, también para L (docs/14 #5)." },
    { id: "D-03", fase: "U", tipo: "decision", estado: "descartado", titulo: "Capturar nombre de la revisión y corte en la UI",
      nota: "Descartado por el usuario: quedan en blanco en el Excel y el auditor los llena a mano (docs/14 #7)." },
    { id: "D-04", fase: "Demo", tipo: "decision", estado: "descartado", titulo: "Usar el AI Gateway de Databricks",
      nota: "Descartado por el usuario: se eligió Azure AI Foundry directo, como en la v1 (docs/14 #14)." },
    { id: "D-05", fase: "D", tipo: "decision", estado: "hecho", titulo: "Artefactos de Docling fuera del paquete (no en models_cache/)",
      nota: "Restricción técnica (límite de 10 MB de Databricks Apps): los modelos de Docling se descargan al primer uso; registrado en docs/14 #16" },
    { id: "D-06", fase: "L", tipo: "decision", estado: "descartado", titulo: "Plan comprimido para hacer todo de golpe",
      nota: "Descartado por el usuario: se eligió ir paso a paso, backend primero con notebooks (docs/13)." },
    { id: "D-07", fase: "L", tipo: "decision", estado: "descartado", titulo: "Simular el LLM en la prueba extremo a extremo (LLM mock)",
      nota: "Descartado por el usuario: modelos reales siempre (CLAUDE.md regla 4)." },
    { id: "D-08", fase: "L", tipo: "decision", estado: "descartado", titulo: "Lectura automática del secret scope de Databricks en config.py",
      nota: "Descartado por el usuario: no portar los settings de la v6 con databricks-sdk/dbutils; se eligió una línea comentada con dbutils.secrets.get en el notebook.", commit: "23db7c8" },
    { id: "D-09", fase: "L", tipo: "decision", estado: "descartado", titulo: "Doc de implementación dentro de docs/ como docs/16",
      nota: "Descartado por el usuario: se eligió la carpeta aparte implementacion/README.md, separando spec y lo implementado.", commit: "f705ca3" },
    { id: "D-10", fase: "Demo", tipo: "decision", estado: "descartado", titulo: "Embeddings con un modelo de Databricks (Foundation Model APIs)",
      nota: "Descartado por el usuario: embeddings de Foundry en Databricks Free y en la demo." },
    { id: "D-11", fase: "D", tipo: "decision", estado: "descartado", titulo: "App mínima con /api/health en Databricks antes de la fase D",
      nota: "Descartado por el usuario: por ahora solo notebook; la app llega en D0/D1." },
    { id: "D-12", fase: "D", tipo: "decision", estado: "descartado", titulo: "Desplegar la app / rama deploy al estilo v6 ahora",
      nota: "Descartado por el usuario: no necesita despliegue todavía; queda para la fase D." },
    { id: "D-13", fase: "L", tipo: "decision", estado: "descartado", titulo: "Cerrar los hitos de la fase L también en el stage dev",
      nota: "Descartado por el usuario: se cierran solo en sandbox; dev es opcional (docs/13, 14bbfe6)." },
    { id: "D-14", fase: "L", tipo: "decision", estado: "descartado", titulo: "Aceptar sin código el riesgo residual de prompt injection",
      nota: "Descartado por el usuario: se eligió un chequeo simple en L4 (docs/14 #18); ver S-01." },
    { id: "D-15", fase: "L", tipo: "decision", estado: "descartado", titulo: "Dejar al product-owner sin Edit, o regla deny/hook en settings.json",
      nota: "Descartado por el usuario: Edit restringido por instrucción (solo datos.js) y verificación del agente principal con git (CLAUDE.md)." },
    { id: "D-16", fase: "L", tipo: "decision", estado: "descartado", titulo: "Instalar Docker Model Runner en la Raspberry",
      nota: "Descartado por el usuario: DMR se usa en la MacBook (stage dev); la Pi usa Groq + Ollama (sandbox)." },
    { id: "D-17", fase: "L", tipo: "decision", estado: "descartado", titulo: "Publicar los commits con el correo personal del autor",
      nota: "Descartado por el usuario: se usa la dirección noreply de GitHub en los commits publicados." },
    { id: "D-18", fase: "L", tipo: "actividad", estado: "descartado", titulo: "Cambiar el .env.example (plantilla del .env o modelos DMR)",
      nota: "Descartado por el usuario: lo resolvió por su cuenta." },
    { id: "D-19", fase: "L", tipo: "decision", estado: "descartado", titulo: "Versionar el manual técnico en PDF",
      nota: "Descartado por el usuario: ignorado y retirado de todo el historial; la fuente de verdad es el Markdown de docs/.", commit: "6dec1f6" },

    // ── Decisiones del usuario sobre QA (docs/14 #19 y docs/13) ──
    { id: "D-20", fase: "L", tipo: "decision", estado: "hecho", titulo: "Sin historias de usuario nuevas: el QA valida los RF/RNF",
      nota: "qa-ia valida los RF/RNF de docs/04 y los criterios de docs/13; trazabilidad en qa/trazabilidad.md (docs/14 #19)." },
    { id: "D-21", fase: "L", tipo: "decision", estado: "hecho", titulo: "Framework de evaluación de IA en desarrollo: DeepEval",
      nota: "Elegido frente a RAGAS por menos dependencias y sin LangChain. Solo en desarrollo y sin telemetría; se usa desde L3 (docs/14 #19, docs/13)." },
    { id: "D-22", fase: "L", tipo: "decision", estado: "hecho", titulo: "Databricks CLI para el QA",
      nota: "Lectura libre; ejecutar pruebas en el workspace Free solo con aprobación del usuario (docs/14 #19)." },
    { id: "D-23", fase: "L", tipo: "decision", estado: "hecho", titulo: "QA al cerrar cada hito: coverage ≥ 80 % y APROBADO de qa-ia",
      nota: "Coverage ≥ 80 % de la lógica determinista (pytest -m \"not integracion\" --cov); sin APROBADO de qa-ia el hito no se cierra (docs/14 #19, docs/13)." },
    { id: "D-24", fase: "L", tipo: "actividad", estado: "descartado", titulo: "Conocimiento de las NOGAI (Normas Globales de Auditoría Interna del IIA) en qa-ia",
      nota: "Descartado por el usuario: lo pidió y luego pidió eliminarlo; el agente qa-ia quedó como estaba antes, sin las NOGAI." },
    { id: "D-25", fase: "L", tipo: "decision", estado: "hecho", titulo: "Pasada base de qa-ia sobre L0 y L1",
      nota: "Aprobada por el usuario y hecha: 163 unitarias, coverage 92 %, 8 de integración; qa-ia APROBADO para L0 y L1 (qa/trazabilidad.md).", commit: "256530e" },
    { id: "D-26", fase: "L", tipo: "decision", estado: "hecho", titulo: "Confirmar las 18 descartadas cargadas en la actualización anterior",
      nota: "Confirmadas por el usuario: D-01..D-19 (salvo D-05) siguen descartadas tal cual." },

    // ── Decisiones del usuario sobre ramas, ingesta y forma de trabajo ──
    { id: "D-27", fase: "L", tipo: "decision", estado: "hecho", titulo: "Ramas cortas desde main con worktree propio y SemVer 0.x por hito",
      nota: "GitHub flow con prefijos de Conventional Commits; tags v0.1.0 = L0 ... v0.7.0 = L6, v1.0.0 = demo (docs/14 #20).", commit: "ffc1b51" },
    { id: "D-28", fase: "L", tipo: "decision", estado: "hecho", titulo: "PDF reparado: se acepta con advertencia; ERR-ING-003 solo si el texto no alcanza SCAN_TEXT_RATIO",
      nota: "Decisión vigente del usuario (docs/14 #21, 5519d13): un PDF reparado (truncado o con xref dañada) se acepta con advertencia y solo se rechaza con ERR-ING-003 si el texto no alcanza SCAN_TEXT_RATIO. Historial: antes (eda0014) todo PDF reparado se rechazaba con ERR-ING-003; el usuario cambió de decisión. qa-ia APROBADO: 168 unitarias passed, coverage 91 %, 8 de integración con Groq + bge-m3.", commit: "5519d13" },
    { id: "D-29", fase: "L", tipo: "decision", estado: "hecho", titulo: "Reportes cortos con la salida literal de las herramientas",
      nota: "Preferencia del usuario, recogida en los agentes.", commit: "214cc5e" },

    // ── Pospuestas a V2 ──
    { id: "V-01", fase: "V2", tipo: "pendiente", estado: "por_hacer", titulo: "Renombrar docs/ a specs/",
      nota: "Pospuesto a después de la demo." },
    { id: "V-02", fase: "V2", tipo: "pendiente", estado: "por_hacer", titulo: "granite-docling (extracción) y qwen3-reranker (cross-encoder) de DMR",
      nota: "Fuera del plan del MVP (docs/15)." },
    { id: "V-03", fase: "V2", tipo: "seguridad", estado: "por_hacer", titulo: "Fijar dependencias transitivas con un lock",
      nota: "Pendiente de appsec (implementacion/README.md)." },
    { id: "V-05", fase: "V2", tipo: "seguridad", estado: "por_hacer", titulo: "PDF truncado con texto en ≥ 60 % de las páginas: aceptar con advertencia",
      nota: "To-be por decisión del usuario, fase V2: se acepta con advertencia y paginas cuenta las vacías. Referencia: implementacion/README.md." },
    { id: "V-04", fase: "V2", tipo: "seguridad", estado: "por_hacer", titulo: "Validar PDFs en subproceso con límite de memoria",
      nota: "Pendiente de appsec para V2; en D0 basta tope en streaming y timeout (S-03)." },

    // ── To-be de appsec (observaciones que el usuario dejó para después) ──
    { id: "S-09", fase: "L", tipo: "seguridad", estado: "revision", titulo: "L2: timeout por documento al parsear PDFs (hito L2)",
      nota: "El timeout con hilos (ThreadPoolExecutor) no corta Docling: el hilo sigue corriendo. Decisión del usuario: timeout en un subproceso con terminate(). Pendiente de corregir y re-verificar por appsec." },
    { id: "S-11", fase: "L", tipo: "seguridad", estado: "por_hacer", titulo: "L2: regex ^\\s* cuadrático y llamar a validar_pdf antes de Docling",
      nota: "Hallazgo de appsec: la regex ^\\s* es cuadrática (8.000 saltos de línea tardan 9 s). Además, el seccionado debe llamar a validar_pdf antes de Docling." },
    { id: "S-12", fase: "L", tipo: "seguridad", estado: "por_hacer", titulo: "L2: quitar el fallback simulado de Docling (regla 4)",
      nota: "Hallazgo de la auditoría: el fallback simulado de Docling contradice CLAUDE.md regla 4 (modelos reales, nunca simulados)." },
    { id: "S-10", fase: "D", tipo: "seguridad", estado: "por_hacer", titulo: "Llevar la advertencia de PDF reparado a la API y al Excel (D0/L5)",
      nota: "To-be por decisión del usuario. Hitos D0 y L5. Referencia: implementacion/README.md." },
  ],

  // Historial breve: una línea por push (lo más reciente arriba).
  historial: [
    { fecha: "2026-10-06", texto: "Auditoría de L2: vuelve a en_curso (esqueleto de agy sin APROBADO de qa-ia, Docling sin instalar, criterio sin medir); S-09 a revisión; tarjetas P-06..P-10, S-11, S-12." },
    { fecha: "2026-10-06", texto: "PDF reparado se acepta con advertencia (D-28, qa-ia aprobado); to-be de appsec S-09, S-10, V-05; tags v0.1.0/v0.2.0 pendientes de publicar (A-10)" },
    { fecha: "2026-10-06", texto: "v0.1.0 y v0.2.0: L0 y L1 con QA aprobado; ramas cortas y SemVer" },
    { fecha: "2026-10-06", texto: "Agente qa-ia con sus skills y decisiones de QA; tablero con descartadas" },
    { fecha: "2026-10-06", texto: "El tablero incluye las actividades descartadas y pospuestas discutidas en la sesión" },
    { fecha: "2026-10-06", texto: "Creación del tablero de avance; el product-owner lo actualiza antes de cada push." },
    { fecha: "2026-10-06", texto: "L1 cerrado: ingesta con validación y clasificador (Groq real)." },
    { fecha: "2026-10-02", texto: "Stages dev/sandbox/mvp, proveedor DMR y auditoría appsec de L0." },
    { fecha: "2026-10-01", texto: "L0 cerrado: base del backend con Groq + bge-m3 reales. Repo público." },
  ],
};
