// Datos del tablero. Lo actualiza el agente product-owner antes de cada push.
// index.html solo los pinta: no hace falta tocarlo para mover tarjetas.
//
// estado: "por_hacer" | "en_curso" | "revision" | "hecho" | "bloqueado" | "descartado"
//         ("descartado" = cancelado o desestimado; solo lo decide el usuario. La nota empieza
//          por "Descartado por el usuario:" con el motivo y lo que se eligió)
// tipo:   "hito" | "seguridad" | "pendiente" | "decision" | "actividad"
//         ("actividad" = trabajo del proyecto que no es hito: repo, agentes, stages, tablero…)
// fase:   id de una fase de la lista "fases"; lo pospuesto fuera del MVP va en "V2".
// ids:    hitos como en docs/13; P- pendientes, S- seguridad, D- descartadas,
//         V- pospuestas a V2, A- actividades. Nunca se borran tarjetas.
window.TABLERO = {
  actualizado: "2026-10-07",
  rama: "main",
  ultimo_commit: "a1c7f36 Merge rama fix/docling-red-bloqueada",
  demo: "Demo MVP en workspace Azure de pago (stage mvp, Foundry)",

  fases: [
    { id: "L", nombre: "Fase L · Backend en local (notebooks)" },
    { id: "D", nombre: "Fase D · Despliegue en Databricks Free" },
    { id: "U", nombre: "Fase U · Interfaz" },
    { id: "Demo", nombre: "Demo · Azure + Foundry" },
    { id: "V2", nombre: "V2 · Fuera del MVP" },
  ],

  tarjetas: [
    // ── Hitos (docs/13) ──
    { id: "L0", fase: "L", tipo: "hito", estado: "hecho", titulo: "Base: config, errores y cliente de modelos",
      nota: "7/7 chequeos en 00_modelos.ipynb con Groq + bge-m3 reales en sandbox (criterio cumplido en f227b59). Después: Foundry listo para probar, correcciones appsec, stages dev/sandbox/mvp y proveedor DMR. qa-ia APROBADO (256530e, 68455a7): 163 unitarias, coverage 92 %, 8 de integración con Groq + bge-m3; criterios L0-L1 4 de 4 y RF/RNF verificados 1 de 28 (RF-04) según qa/trazabilidad.md. Tag v0.1.0 pendiente de publicar (ver A-10).", commit: "7c802a1" },
    { id: "L1", fase: "L", tipo: "hito", estado: "hecho", titulo: "Ingesta: validación + clasificación",
      nota: "6/6 chequeos en 01_ingesta.ipynb (Groq real). MOCK → manual_control, LA/FT → normativa (0,85). Rechazos con ERR-ING-001..003 y mensaje de negocio; un PDF reparado se acepta con advertencia y solo se rechaza con ERR-ING-003 si el texto no alcanza SCAN_TEXT_RATIO (5519d13, ver D-28). qa-ia APROBADO para el fix del PDF reparado: 168 unitarias passed, coverage 91 %, 8 de integración con Groq + bge-m3. Tag v0.2.0 pendiente de publicar (ver A-10).", commit: "0b4f926" },
    { id: "L2", fase: "L", tipo: "hito", estado: "hecho", titulo: "Seccionado: Docling + cascada de patrones",
      nota: "qa-ia APROBADO e integrado en main. LA/FT 99/99 secciones, 0 falsos positivos ni negativos; reproceso con caché de 47 s a 0,015 s; coverage de extracción 96 %. QA-02 (Media, SIGTERM ignorado) corregido (89a10b2); QA-03 (BAJA, ARTÍCULO ÚNICO=1) diferido al to-be. Exclusión de coverage de docling_worker.main() aprobada por el usuario. Pendiente: que el usuario apruebe el notebook 02 (D-35). Ver implementacion/README.md y qa/trazabilidad.md.", commit: "1657af9" },
    { id: "L3", fase: "L", tipo: "hito", estado: "hecho", titulo: "Recuperación: sub-chunks, embeddings, FAISS, pares",
      nota: "qa-ia APROBADO e integrado en main. Recall 28/30 = 93,3 % (100 % sin las 2 filas por_confirmar); pares candidatos de 637 a 483. Defectos BAJA QA-L3-01..03 corregidos al integrar (686dca4). El recall se repite con la cascada real de L2 (P-13, en curso). Pendiente: que el usuario apruebe el notebook 03 (D-35).", commit: "686dca4" },
    { id: "L4", fase: "L", tipo: "hito", estado: "por_hacer", titulo: "Juez: veredictos, citas verificadas, marcas A/L/R/X/P",
      nota: "MOCK-03 → A, MOCK-01 → L, MOCK-02 → R. Es el próximo hito, después de que el usuario apruebe los notebooks 02, 03 y 05 (D-35)." },
    { id: "L5", fase: "L", tipo: "hito", estado: "hecho", titulo: "Papel de trabajo: Excel Hoja 1 + Hoja 2",
      nota: "qa-ia APROBADO e integrado en main: Excel con marcas A/L/R/X/P y borrador de conclusión con Groq real. Pendiente: abrirlo en Microsoft Excel (P-14) y que el usuario apruebe el notebook 05 (D-35).", commit: "b36e3cc" },
    { id: "L6", fase: "L", tipo: "hito", estado: "por_hacer", titulo: "Extremo a extremo: PDFs → Excel",
      nota: "Tiempos y RAM medidos en la Raspberry." },
    { id: "D0", fase: "D", tipo: "hito", estado: "por_hacer", titulo: "API FastAPI + sesión en memoria" },
    { id: "D1", fase: "D", tipo: "hito", estado: "por_hacer", titulo: "App en Databricks Free (app.yaml, < 10 MB)" },
    { id: "D2", fase: "D", tipo: "hito", estado: "por_hacer", titulo: "Ejemplos precargados (samples/)" },
    { id: "U0", fase: "U", tipo: "hito", estado: "por_hacer", titulo: "UI mínima en verde y blanco" },
    { id: "DEMO", fase: "Demo", tipo: "hito", estado: "por_hacer", titulo: "Ensayo con Foundry y documentos reales" },

    // ── Pendientes y verificaciones ──
    { id: "P-01", fase: "L", tipo: "pendiente", estado: "por_hacer", titulo: "Probar stage dev (MacBook, DMR)",
      nota: "Opcional, no bloquea (docs/13). Lo prueba el usuario." },
    { id: "P-02", fase: "Demo", tipo: "pendiente", estado: "por_hacer", titulo: "Probar stage mvp (Foundry en Databricks)",
      nota: "Celda comentada en 00_modelos.ipynb; token por dbutils." },
    { id: "P-03", fase: "L", tipo: "pendiente", estado: "por_hacer", titulo: "Calibrar SIM_THRESHOLD por stage",
      nota: "Con bge-m3 un par sin relación ya da ~0,50. Se calibra en L3 (docs/14 #1)." },
    { id: "P-04", fase: "L", tipo: "pendiente", estado: "por_hacer", titulo: "Calibrar LLM_CONCURRENCY con Groq gratuito",
      nota: "Ya se vieron 429 en L1. Se calibra en L4 (docs/14 #9)." },
    { id: "P-05", fase: "D", tipo: "pendiente", estado: "por_hacer", titulo: "D0: los metadatos editados por el auditor ganan a los del modelo",
      nota: "Anotado en implementacion/README.md, L1." },
    { id: "P-06", fase: "L", tipo: "pendiente", estado: "hecho", titulo: "L2: cola de 1 worker para Docling + progreso",
      nota: "Cola de 1 worker y progreso por tanda hechos (CLAUDE.md regla 7; do_ocr=False).", commit: "321c377" },
    { id: "P-07", fase: "L", tipo: "pendiente", estado: "hecho", titulo: "L2: cascada completa de seccionado",
      nota: "Cascada multi-esquema con jerarquía validada, integrada en main y aprobada por qa-ia.", commit: "1657af9" },
    { id: "P-08", fase: "L", tipo: "pendiente", estado: "hecho", titulo: "L2: caché por SHA-256 del PDF",
      nota: "Caché SHA-256 hecha; en el notebook 02 la segunda lectura tarda 0,018 s.", commit: "321c377" },
    { id: "P-09", fase: "L", tipo: "pendiente", estado: "hecho", titulo: "L2: medir ≥ 95 % de secciones en la LA/FT con RAM y CPU en la Raspberry",
      nota: "Medido por qa-ia: LA/FT 99/99 secciones, 0 FP/FN. Antes: Docling 2.134.0 instalado. Medido: LA/FT 55 págs en 511 s y 2,97 GB con 2 CPU (antes 300 s y 1,89 GB con 2.55.1; DOCLING_TIMEOUT_S a 1500; implementacion/README.md). Criterio de aceptación de L2 (docs/13) cumplido.", commit: "1657af9" },
    { id: "P-11", fase: "L", tipo: "pendiente", estado: "por_hacer", titulo: "L3: crear el entorno comparador_eval e instalar requirements-eval.txt",
      nota: "Entorno propio para RAGAS (exige openai<2); se usa desde L3 con RAGAS_DO_NOT_TRACK=true (docs/14 #19)." },
    { id: "P-10", fase: "L", tipo: "pendiente", estado: "hecho", titulo: "L2: pruebas de qa-ia para el seccionado",
      nota: "Pruebas de seccionado y extractor con integración real de Docling; qa-ia APROBADO, coverage de extracción 96 %.", commit: "38eff09" },
    { id: "P-12", fase: "L", tipo: "pendiente", estado: "por_hacer", titulo: "Notebooks 02, 03 y 05 listos por stage para que el usuario los apruebe",
      nota: "Siguiente paso antes de L4 (D-35). Los aprueba el usuario." },
    { id: "P-13", fase: "L", tipo: "pendiente", estado: "en_curso", titulo: "L3: repetir el recall con la cascada real de L2",
      nota: "El recall de 93,3 % se repite con la cascada real de L2; en curso." },
    { id: "P-14", fase: "L", tipo: "pendiente", estado: "por_hacer", titulo: "L5: abrir el Excel en Microsoft Excel",
      nota: "Verificación manual pendiente; la hace el usuario." },
    { id: "P-15", fase: "L", tipo: "pendiente", estado: "por_hacer", titulo: "Golden set: confirmar 2 pares por_confirmar (art. 31 -> 4.1 y art. 37 -> V de MOCK-01)",
      nota: "Golden set de 51 pares; las 2 filas por_confirmar las decide el usuario." },

    { id: "P-16", fase: "L", tipo: "pendiente", estado: "por_hacer", titulo: "Conjunto de mejoras tras revisar los notebooks",
      nota: "Pendiente de las pruebas del usuario (7 oct 2026): (a) cambiar DMR_LLM_MODEL de dev a ai/gemma4 (qwen3.5 devuelve respuesta vacía); (b) mensaje claro cuando el LLM devuelve respuesta vacía (finish_reason) en lugar de JSON inválido; (c) revisar el juez de L4 y la conclusión de L5 con gemma4." },

    // ── Seguridad (agente appsec) ──
    { id: "S-01", fase: "L", tipo: "seguridad", estado: "por_hacer", titulo: "L4: chequeo de frases al evaluador → requiere_revision",
      nota: "Decisión del usuario (docs/14 #18)." },
    { id: "S-02", fase: "L", tipo: "seguridad", estado: "por_hacer", titulo: "L5: neutralizar fórmulas en el Excel (CWE-1236)",
      nota: "Todas las celdas de texto, incluidos metadatos y textos del modelo: prefijos =, +, -, @." },
    { id: "S-03", fase: "D", tipo: "seguridad", estado: "por_hacer", titulo: "D0: subidas con nombre generado, tope en streaming y timeout",
      nota: "MuPDF parsea entrada hostil." },
    { id: "S-04", fase: "D", tipo: "seguridad", estado: "por_hacer", titulo: "D0: /api/health sin detalle técnico y con caché",
      nota: "El ping gasta tokens. Además: cargar_prompt nunca con entrada del usuario." },
    { id: "S-05", fase: "L", tipo: "seguridad", estado: "por_hacer", titulo: "L4: rellenar el prompt del juez con rellenar_prompt",
      nota: "Ya existe desde L1 (clasificador). Auditoría appsec de L0." },
    { id: "S-06", fase: "L", tipo: "seguridad", estado: "hecho", titulo: "L1: validar %PDF, MAX_MB, MAX_PAGES y sanear el nombre",
      nota: "Hecho en validation.py; verificado en 01_ingesta.ipynb.", commit: "0b4f926" },
    { id: "S-07", fase: "L", tipo: "seguridad", estado: "hecho", titulo: "QA-01: rellenar_prompt con marcas anidadas o con atributos (MEDIA)",
      nota: "La neutralización de <texto_*> se podía saltar. Corregido y re-verificado por qa-ia (test_rellenar_prompt_marca_anidada_no_reconstruye_el_cierre, test_rellenar_prompt_quita_marca_con_atributos).", commit: "eda0014" },
    { id: "S-08", fase: "L", tipo: "seguridad", estado: "hecho", titulo: "DoS cuadrático en la neutralización de marcas (BAJA)",
      nota: "La neutralización pasa a ser lineal; corregido junto con QA-01.", commit: "eda0014" },

    // ── Actividades del proyecto (no son hitos) ──
    { id: "A-01", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Repo público basaravia/comparador-normas-v2",
      nota: "Creado y sincronizado. PDF del manual retirado de todo el historial; commits con la dirección noreply de GitHub.", commit: "6dec1f6" },
    { id: "A-02", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Worktree comparador-normas-v2-local con la rama feat/fase-l-local",
      nota: "Toda la fase L se trabajó en esta rama hasta L1; integrada en main y retirada (ver A-09)." },
    { id: "A-03", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Agente product-owner",
      nota: "Autoridad solo sobre plan y alcance (8da0562); supervisa el doc de implementación (implementacion/README.md, f705ca3).", commit: "d7233b4" },
    { id: "A-04", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Agente appsec (ciberseguridad aplicativa)",
      nota: "Revisa cada commit (ad885f8, 99e5e9c). Auditoría inicial de L0 con correcciones.", commit: "a8292be" },
    { id: "A-05", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Stages dev/sandbox/mvp y proveedor Docker Model Runner",
      nota: "Un archivo config/stages/<stage>.env por stage, elegido con STAGE (docs/14 #13).", commit: "7c802a1" },
    { id: "A-06", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Tablero de avance estilo Jira",
      nota: "Creado en f48c1bd. Ampliado con la columna Descartado y las actividades descartadas y pospuestas (48e6ad5).", commit: "f48c1bd" },
    { id: "A-07", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Agente qa-ia (QA de IA para auditoría financiera) y sus skills",
      nota: "Agente .claude/agents/qa-ia.md con las skills qa-pruebas, qa-trazabilidad y qa-eval-ia (.claude/skills/). Escribe solo en tests/, qa/ y pytest.ini; el agente principal lo verifica con git.", commit: "d9f46cf" },

    { id: "A-08", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Script tablero/servir.sh para ver el tablero en la red local",
      nota: "Sirve el tablero en la LAN sin publicarlo.", commit: "e41fbb2" },
    { id: "A-10", fase: "L", tipo: "actividad", estado: "por_hacer", titulo: "Publicar main y tags v0.1.0/v0.2.0",
      nota: "Publicar main y tags v0.1.0/v0.2.0 (bloqueado por falso positivo del guardián en tests/test_config.py: clave de prueba inventada; decisión del usuario pendiente)." },
    { id: "A-11", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Auditoría de L2 por PO, qa-ia y appsec",
      nota: "Resultado: L2 vuelve a en_curso y S-09 a revisión; hallazgos en P-06..P-10, S-11 y S-12." },
    { id: "A-12", fase: "L", tipo: "actividad", estado: "hecho", titulo: "La rama de agy con L2 subió sin revisión",
      nota: "Registrado como hecho del proceso, sin culpar a nadie: la rama llegó sin pasar por appsec, product-owner ni qa-ia (CLAUDE.md). Por eso se audita a posteriori (A-11)." },
    { id: "D-30", fase: "L", tipo: "decision", estado: "hecho", titulo: "Reabrir y completar L2 sobre feat/l2-seccionado; timeout de Docling en subproceso",
      nota: "Decisiones del usuario: L2 se reabre y se completa en feat/l2-seccionado; el timeout de Docling va en un subproceso con terminate() (ver S-09)." },
    { id: "A-13", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Mediciones de Docling en la Raspberry limitada a 2 CPU",
      nota: "3 págs: 29,5 s y 1,5 GB. LA/FT 55 págs: 300 s y 1,9 GB. Registradas en implementacion/README.md." },
    { id: "A-14", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Entorno comparador_docling y Docling también en comparador_v2",
      nota: "Entorno comparador_docling creado y docling instalado además en comparador_v2. Hallazgo de la Pi: /tmp es tmpfs de 4 GB y la instalación falló hasta usar TMPDIR en disco." },
    { id: "D-31", fase: "L", tipo: "decision", estado: "hecho", titulo: "Aceptar y documentar el riesgo de 59 CVE de docling==2.55.1",
      nota: "Descartado por el usuario: aceptar el riesgo de 59 CVE; el usuario decidió actualizar ahora; docs/14 #22" },
    { id: "D-32", fase: "L", tipo: "decision", estado: "hecho", titulo: "Actualizar Docling a 2.134.0 con pila sin CVE (docs/14 #22)",
      nota: "Decisión del usuario ('Actualizar ahora'): docling 2.134.0 + pillow 12.3.0 + lxml 6.1.3 + transformers 5.19.0; pip-audit 0 vulnerabilidades en requirements.txt y en el entorno recreado. Costo: LA/FT 511 s y 2,97 GB; DOCLING_TIMEOUT_S a 1500.", commit: "1285037" },
    { id: "A-15", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Entorno comparador_v2 recreado desde cero con requirements-dev.txt",
      nota: "Valida la instalación limpia; pip-audit 0 vulnerabilidades. Trabajo en la rama fix/docling-cve (sale de feat/l2-extraccion-docling)." },
    { id: "A-16", fase: "L", tipo: "actividad", estado: "por_hacer", titulo: "CI de GitHub Actions (rama chore/ci-github-actions)",
      nota: "Implementado en la rama chore/ci-github-actions, sin integrar. Pospuesto por el usuario: MVP primero." },
    { id: "A-17", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Golden set de 51 pares",
      nota: "Golden set para medir el recall de L3; 2 filas por_confirmar (P-15)." },
    { id: "D-35", fase: "L", tipo: "decision", estado: "hecho", titulo: "Ritmo nuevo: un hito a la vez, notebook como puerta de aprobación",
      nota: "Decisión del usuario (7 oct 2026): un hito a la vez; el notebook es la puerta de aprobación del usuario; revisores ligeros por commit; tablero una vez por hito. Prioridad MVP sobre perfección técnica. Orden: notebooks 02, 03 y 05 por stage, luego L4." },
    { id: "D-36", fase: "L", tipo: "decision", estado: "hecho", titulo: "Excluir docling_worker.main() del coverage",
      nota: "Aprobado por el usuario al cerrar L2: el punto de entrada del subproceso queda fuera del coverage." },
    { id: "A-09", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Integrar la rama larga feat/fase-l-local en main y retirarla",
      nota: "Integrada en main y retirada en este push; desde ahora ramas cortas desde main (D-27)." },

    // ── Descartadas por el usuario (y decisiones relacionadas) ──
    { id: "D-01", fase: "L", tipo: "decision", estado: "descartado", titulo: "Vía 2 en una tercera hoja del Excel",
      nota: "Descartado por el usuario: sin tercera hoja; se eligió un bloque al final del anexo, Hoja 2 (docs/14 #4)." },
    { id: "D-02", fase: "L", tipo: "decision", estado: "descartado", titulo: "Respaldo de hasta 2 secciones de manual para la marca L",
      nota: "Descartado por el usuario: se eligió 1 sección de respaldo por artículo, también para L (docs/14 #5)." },
    { id: "D-03", fase: "U", tipo: "decision", estado: "descartado", titulo: "Capturar nombre de la revisión y corte en la UI",
      nota: "Descartado por el usuario: quedan en blanco en el Excel y el auditor los llena a mano (docs/14 #7)." },
    { id: "D-04", fase: "Demo", tipo: "decision", estado: "descartado", titulo: "Usar el AI Gateway de Databricks",
      nota: "Descartado por el usuario: se eligió Azure AI Foundry directo, como en la v1 (docs/14 #14)." },
    { id: "D-05", fase: "D", tipo: "decision", estado: "hecho", titulo: "Artefactos de Docling fuera del paquete (no en models_cache/)",
      nota: "Restricción técnica (límite de 10 MB de Databricks Apps): los modelos de Docling se descargan al primer uso; registrado en docs/14 #16" },
    { id: "D-06", fase: "L", tipo: "decision", estado: "descartado", titulo: "Plan comprimido para hacer todo de golpe",
      nota: "Descartado por el usuario: se eligió ir paso a paso, backend primero con notebooks (docs/13)." },
    { id: "D-07", fase: "L", tipo: "decision", estado: "descartado", titulo: "Simular el LLM en la prueba extremo a extremo (LLM mock)",
      nota: "Descartado por el usuario: modelos reales siempre (CLAUDE.md regla 4)." },
    { id: "D-08", fase: "L", tipo: "decision", estado: "descartado", titulo: "Lectura automática del secret scope de Databricks en config.py",
      nota: "Descartado por el usuario: no portar los settings de la v6 con databricks-sdk/dbutils; se eligió una línea comentada con dbutils.secrets.get en el notebook.", commit: "23db7c8" },
    { id: "D-09", fase: "L", tipo: "decision", estado: "descartado", titulo: "Doc de implementación dentro de docs/ como docs/16",
      nota: "Descartado por el usuario: se eligió la carpeta aparte implementacion/README.md, separando spec y lo implementado.", commit: "f705ca3" },
    { id: "D-10", fase: "Demo", tipo: "decision", estado: "descartado", titulo: "Embeddings con un modelo de Databricks (Foundation Model APIs)",
      nota: "Descartado por el usuario: embeddings de Foundry en Databricks Free y en la demo." },
    { id: "D-11", fase: "D", tipo: "decision", estado: "descartado", titulo: "App mínima con /api/health en Databricks antes de la fase D",
      nota: "Descartado por el usuario: por ahora solo notebook; la app llega en D0/D1." },
    { id: "D-12", fase: "D", tipo: "decision", estado: "descartado", titulo: "Desplegar la app / rama deploy al estilo v6 ahora",
      nota: "Descartado por el usuario: no necesita despliegue todavía; queda para la fase D." },
    { id: "D-13", fase: "L", tipo: "decision", estado: "descartado", titulo: "Cerrar los hitos de la fase L también en el stage dev",
      nota: "Descartado por el usuario: se cierran solo en sandbox; dev es opcional (docs/13, 14bbfe6)." },
    { id: "D-14", fase: "L", tipo: "decision", estado: "descartado", titulo: "Aceptar sin código el riesgo residual de prompt injection",
      nota: "Descartado por el usuario: se eligió un chequeo simple en L4 (docs/14 #18); ver S-01." },
    { id: "D-15", fase: "L", tipo: "decision", estado: "descartado", titulo: "Dejar al product-owner sin Edit, o regla deny/hook en settings.json",
      nota: "Descartado por el usuario: Edit restringido por instrucción (solo datos.js) y verificación del agente principal con git (CLAUDE.md)." },
    { id: "D-16", fase: "L", tipo: "decision", estado: "descartado", titulo: "Instalar Docker Model Runner en la Raspberry",
      nota: "Descartado por el usuario: DMR se usa en la MacBook (stage dev); la Pi usa Groq + Ollama (sandbox)." },
    { id: "D-17", fase: "L", tipo: "decision", estado: "descartado", titulo: "Publicar los commits con el correo personal del autor",
      nota: "Descartado por el usuario: se usa la dirección noreply de GitHub en los commits publicados." },
    { id: "D-18", fase: "L", tipo: "actividad", estado: "descartado", titulo: "Cambiar el .env.example (plantilla del .env o modelos DMR)",
      nota: "Descartado por el usuario: lo resolvió por su cuenta." },
    { id: "D-19", fase: "L", tipo: "decision", estado: "descartado", titulo: "Versionar el manual técnico en PDF",
      nota: "Descartado por el usuario: ignorado y retirado de todo el historial; la fuente de verdad es el Markdown de docs/.", commit: "6dec1f6" },

    // ── Decisiones del usuario sobre QA (docs/14 #19 y docs/13) ──
    { id: "D-20", fase: "L", tipo: "decision", estado: "hecho", titulo: "Sin historias de usuario nuevas: el QA valida los RF/RNF",
      nota: "qa-ia valida los RF/RNF de docs/04 y los criterios de docs/13; trazabilidad en qa/trazabilidad.md (docs/14 #19)." },
    { id: "D-21", fase: "L", tipo: "decision", estado: "descartado", titulo: "Framework de evaluación de IA en desarrollo: DeepEval",
      nota: "Descartado por el usuario: DeepEval; se eligió RAGAS (docs/14 #19). Motivo: deepeval 4.2.8 choca con transformers 5.x." },
    { id: "D-33", fase: "L", tipo: "decision", estado: "hecho", titulo: "RAGAS en entorno propio comparador_eval",
      nota: "Decisión del usuario ('usa otro framework, ragas o langfuse'): RAGAS con requirements-eval.txt y RAGAS_DO_NOT_TRACK=true, en entorno propio por incompatibilidad de dependencias (docs/14 #19).", commit: "1285037" },
    { id: "D-34", fase: "L", tipo: "decision", estado: "descartado", titulo: "Langfuse como framework de evaluación",
      nota: "Descartado por el usuario: Langfuse, porque necesita un servidor y no pueden salir documentos del banco; se eligió RAGAS (docs/14 #19)." },
    { id: "D-22", fase: "L", tipo: "decision", estado: "hecho", titulo: "Databricks CLI para el QA",
      nota: "Lectura libre; ejecutar pruebas en el workspace Free solo con aprobación del usuario (docs/14 #19)." },
    { id: "D-23", fase: "L", tipo: "decision", estado: "hecho", titulo: "QA al cerrar cada hito: coverage ≥ 80 % y APROBADO de qa-ia",
      nota: "Coverage ≥ 80 % de la lógica determinista (pytest -m \"not integracion\" --cov); sin APROBADO de qa-ia el hito no se cierra (docs/14 #19, docs/13)." },
    { id: "D-24", fase: "L", tipo: "actividad", estado: "descartado", titulo: "Conocimiento de las NOGAI (Normas Globales de Auditoría Interna del IIA) en qa-ia",
      nota: "Descartado por el usuario: lo pidió y luego pidió eliminarlo; el agente qa-ia quedó como estaba antes, sin las NOGAI." },
    { id: "D-25", fase: "L", tipo: "decision", estado: "hecho", titulo: "Pasada base de qa-ia sobre L0 y L1",
      nota: "Aprobada por el usuario y hecha: 163 unitarias, coverage 92 %, 8 de integración; qa-ia APROBADO para L0 y L1 (qa/trazabilidad.md).", commit: "256530e" },
    { id: "D-26", fase: "L", tipo: "decision", estado: "hecho", titulo: "Confirmar las 18 descartadas cargadas en la actualización anterior",
      nota: "Confirmadas por el usuario: D-01..D-19 (salvo D-05) siguen descartadas tal cual." },

    // ── Decisiones del usuario sobre ramas, ingesta y forma de trabajo ──
    { id: "D-27", fase: "L", tipo: "decision", estado: "hecho", titulo: "Ramas cortas desde main con worktree propio y SemVer 0.x por hito",
      nota: "GitHub flow con prefijos de Conventional Commits; tags v0.1.0 = L0 ... v0.7.0 = L6, v1.0.0 = demo (docs/14 #20).", commit: "ffc1b51" },
    { id: "D-28", fase: "L", tipo: "decision", estado: "hecho", titulo: "PDF reparado: se acepta con advertencia; ERR-ING-003 solo si el texto no alcanza SCAN_TEXT_RATIO",
      nota: "Decisión vigente del usuario (docs/14 #21, 5519d13): un PDF reparado (truncado o con xref dañada) se acepta con advertencia y solo se rechaza con ERR-ING-003 si el texto no alcanza SCAN_TEXT_RATIO. Historial: antes (eda0014) todo PDF reparado se rechazaba con ERR-ING-003; el usuario cambió de decisión. qa-ia APROBADO: 168 unitarias passed, coverage 91 %, 8 de integración con Groq + bge-m3.", commit: "5519d13" },
    { id: "D-29", fase: "L", tipo: "decision", estado: "hecho", titulo: "Reportes cortos con la salida literal de las herramientas",
      nota: "Preferencia del usuario, recogida en los agentes.", commit: "214cc5e" },

    { id: "A-18", fase: "L", tipo: "actividad", estado: "hecho", titulo: "Docling con la red corporativa bloqueada, defaults.env y notebooks en macOS",
      nota: "Arreglo de Docling con red bloqueada (a1c7f36): el subproceso hereda proxy y certificados; error ERR-EXT-004 con mensaje de negocio; modelos locales sin red con HF_HUB_OFFLINE=1 (procedimiento en documentos/LEEME.md). Verificado en la Pi sin red: 43 bloques en 33 s. Corregidos también: comentarios de defaults.env leídos como valor (652300f) y notebooks compatibles con macOS (873771b).", commit: "a1c7f36" },

    // ── Pospuestas a V2 ──
    { id: "V-01", fase: "V2", tipo: "pendiente", estado: "por_hacer", titulo: "Renombrar docs/ a specs/",
      nota: "Pospuesto a después de la demo." },
    { id: "V-02", fase: "V2", tipo: "pendiente", estado: "por_hacer", titulo: "granite-docling (extracción) y qwen3-reranker (cross-encoder) de DMR",
      nota: "Fuera del plan del MVP (docs/15)." },
    { id: "V-03", fase: "V2", tipo: "seguridad", estado: "por_hacer", titulo: "Fijar dependencias transitivas con un lock",
      nota: "Pendiente de appsec (implementacion/README.md)." },
    { id: "V-05", fase: "V2", tipo: "seguridad", estado: "por_hacer", titulo: "PDF truncado con texto en ≥ 60 % de las páginas: aceptar con advertencia",
      nota: "To-be por decisión del usuario, fase V2: se acepta con advertencia y paginas cuenta las vacías. Referencia: implementacion/README.md." },
    { id: "V-06", fase: "V2", tipo: "seguridad", estado: "hecho", titulo: "Revisar CVE de Docling antes de producción (probar versión más nueva y re-medir)",
      nota: "Resuelto ahora por decisión del usuario (D-32): docling 2.134.0, pip-audit 0 vulnerabilidades; re-medido: LA/FT 511 s y 2,97 GB (docs/14 #22).", commit: "1285037" },
    { id: "V-04", fase: "V2", tipo: "seguridad", estado: "por_hacer", titulo: "Validar PDFs en subproceso con límite de memoria",
      nota: "Pendiente de appsec para V2; en D0 basta tope en streaming y timeout (S-03)." },

    { id: "V-07", fase: "V2", tipo: "seguridad", estado: "por_hacer", titulo: "PyMuPDF sin timeout en el proceso principal (MEDIA)",
      nota: "To-be de appsec/QA, para después de L6." },
    { id: "V-08", fase: "V2", tipo: "pendiente", estado: "por_hacer", titulo: "QA-03 (BAJA): ARTÍCULO ÚNICO = 1",
      nota: "Diferido al to-be por decisión del usuario al aprobar L2." },
    { id: "V-09", fase: "V2", tipo: "pendiente", estado: "por_hacer", titulo: "To-be BAJA: .search(), numero(), validación de cifras por floats",
      nota: "Tres observaciones de baja severidad para después del MVP." },
    { id: "V-10", fase: "V2", tipo: "pendiente", estado: "por_hacer", titulo: "classifier.py con 79 % de coverage",
      nota: "Subir a 80 % o más en el to-be." },
    { id: "V-11", fase: "V2", tipo: "pendiente", estado: "por_hacer", titulo: "Diferenciar el modelo fundacional por etapa del flujo",
      nota: "To-be (7 oct 2026): usar un modelo distinto según la tarea, p. ej. uno ligero y sin razonamiento para ingesta/clasificación y conclusión, y uno más capaz para el juez de L4; configurable por variable de entorno por etapa (LLM por etapa) en cada stage (dev, sandbox, mvp). Origen: con qwen3.5 (modelo de razonamiento) el clasificador de la ingesta devolvía respuesta vacía en dev (DMR) y con gemma4 funcionó. El usuario decide cuándo." },
    { id: "V-12", fase: "V2", tipo: "pendiente", estado: "por_hacer", titulo: "Ingesta: metadatos y tipo con reglas deterministas primero y LLM de respaldo",
      nota: "Pospuesto: propuesta B del análisis. El usuario decidió el 7 oct 2026 dejar la ingesta como está (LLM en ingesta, opción A) por ahora; queda como posible mejora." },
    { id: "V-13", fase: "V2", tipo: "pendiente", estado: "por_hacer", titulo: "Borrar la rama auxiliar aux/docling-modelos de GitHub y el tar local de la Pi",
      nota: "To-be, lo decide el usuario. La rama (6 trozos de 90 MB, ~470 MB de modelos públicos de Docling) se subió para que el usuario los descargue en su Mac sin estar en la misma red; el usuario decidió no borrarla todavía. Incluye también eliminar ~/docling-modelos.tar.gz en la Pi y el worktree wt-aux-docling." },
    { id: "V-14", fase: "V2", tipo: "pendiente", estado: "por_hacer", titulo: "Evaluar granite-docling (DMR) como extractor opcional de dev",
      nota: "To-be, no es prioridad. Alternativa que mencionó el usuario: cambia la estructura de la extracción (no validada con el seccionado de L2) y dev y mvp extraerían distinto. Relacionada con V-02." },

    // ── To-be de appsec (observaciones que el usuario dejó para después) ──
    { id: "S-09", fase: "L", tipo: "seguridad", estado: "hecho", titulo: "L2: timeout por documento al parsear PDFs (hito L2)",
      nota: "Timeout en subproceso con terminate y killpg (decisión del usuario). Verificado: corta a 2,0 s y deja 0 procesos vivos.", commit: "321c377" },
    { id: "S-11", fase: "L", tipo: "seguridad", estado: "por_hacer", titulo: "L2: regex ^\\s* cuadrático y llamar a validar_pdf antes de Docling",
      nota: "Hecho (321c377): el seccionado llama a validar_pdf antes de Docling. Pendiente: la regex ^\\s* es cuadrática (8.000 saltos de línea tardan 9 s)." },
    { id: "S-12", fase: "L", tipo: "seguridad", estado: "hecho", titulo: "L2: quitar el fallback simulado de Docling (regla 4)",
      nota: "Fallback simulado quitado; la extracción es real (CLAUDE.md regla 4).", commit: "321c377" },
    { id: "S-13", fase: "L", tipo: "seguridad", estado: "hecho", titulo: "QA-02: el subproceso de Docling ignoraba SIGTERM (MEDIA)",
      nota: "Corregido: SIGKILL a los 5 s si el hijo ignora SIGTERM (RNF-02); re-verificado por qa-ia.", commit: "89a10b2" },
    { id: "S-14", fase: "L", tipo: "seguridad", estado: "hecho", titulo: "Settings sin secretos en repr y config/.env local limpiado",
      nota: "Los secretos ya no salen en repr de Settings; el .env local solo conserva STAGE y GROQ_API_KEY.", commit: "686dca4" },
    { id: "S-10", fase: "D", tipo: "seguridad", estado: "por_hacer", titulo: "Llevar la advertencia de PDF reparado a la API y al Excel (D0/L5)",
      nota: "To-be por decisión del usuario. Hitos D0 y L5. Referencia: implementacion/README.md." },
  ],

  // Historial breve: una línea por push (lo más reciente arriba).
  historial: [
    { fecha: "2026-10-07", texto: "main (a1c7f36): Docling funciona con la red corporativa bloqueada (proxy y certificados heredados, ERR-EXT-004, modelos locales con HF_HUB_OFFLINE=1; verificado en la Pi: 43 bloques en 33 s); defaults.env (652300f) y notebooks en macOS (873771b) corregidos; nuevas tarjetas A-18, V-13 (borrar rama aux/docling-modelos, decide el usuario) y V-14 (granite-docling en dev)." },
    { fecha: "2026-10-07", texto: "main (c031b78): hecho carpetas documentos/normas y documentos/manuales (NORMAS_DIR, MANUALES_DIR), defaults.env y .env.example, barras de progreso tqdm en notebooks 01, 02, 03 y 05; nuevas tarjetas P-16 (mejoras tras revisar notebooks), V-11 (modelo por etapa) y V-12 (ingesta con reglas primero, pospuesta por decisión del usuario)." },
    { fecha: "2026-10-07", texto: "main (686dca4): L2, L3 y L5 con APROBADO de qa-ia; QA-02 corregido; golden set de 51 pares; nuevo ritmo (D-35); CI pospuesto (A-16); to-be V-07..V-10; próximo: notebooks 02, 03, 05 y luego L4." },
    { fecha: "2026-10-06", texto: "Rama fix/docling-cve: Docling 2.134.0 con pila sin CVE (D-32, V-06 hecha; D-31 descartada); RAGAS reemplaza a DeepEval (D-21 descartada, D-33, D-34); L2 sigue en curso." },
    { fecha: "2026-10-06", texto: "L2 sigue en curso: extracción real con Docling (321c377), cola de 1 worker, caché y timeout en subproceso; P-06, P-08, S-09, S-12 hechas; mediciones en la Pi; CVE de Docling aceptados (D-31, V-06)." },
    { fecha: "2026-10-06", texto: "Auditoría de L2: vuelve a en_curso (esqueleto de agy sin APROBADO de qa-ia, Docling sin instalar, criterio sin medir); S-09 a revisión; tarjetas P-06..P-10, S-11, S-12." },
    { fecha: "2026-10-06", texto: "PDF reparado se acepta con advertencia (D-28, qa-ia aprobado); to-be de appsec S-09, S-10, V-05; tags v0.1.0/v0.2.0 pendientes de publicar (A-10)" },
    { fecha: "2026-10-06", texto: "v0.1.0 y v0.2.0: L0 y L1 con QA aprobado; ramas cortas y SemVer" },
    { fecha: "2026-10-06", texto: "Agente qa-ia con sus skills y decisiones de QA; tablero con descartadas" },
    { fecha: "2026-10-06", texto: "El tablero incluye las actividades descartadas y pospuestas discutidas en la sesión" },
    { fecha: "2026-10-06", texto: "Creación del tablero de avance; el product-owner lo actualiza antes de cada push." },
    { fecha: "2026-10-06", texto: "L1 cerrado: ingesta con validación y clasificador (Groq real)." },
    { fecha: "2026-10-02", texto: "Stages dev/sandbox/mvp, proveedor DMR y auditoría appsec de L0." },
    { fecha: "2026-10-01", texto: "L0 cerrado: base del backend con Groq + bge-m3 reales. Repo público." },
  ],
};
